version: "3"

volumes:
  postgres-data: {}

services:
  bot:
    build:
      context: .
      args:
        BUILD_ENV: dev
    command: python main.py
    depends_on:
      - postgres
    volumes:
      - ./src:/app:z
      - type: bind
        source: ./pyproject.toml
        target: /app/pyproject.toml
    tty: true
    env_file:
      - ./.env

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data:Z
    env_file:
      - ./.env
